import type { Locale } from "./i18n";

// Describes the implementations in src/taf, including departures from the papers.
// Each entry contains a short purpose and an expandable mechanism/interpretation.
type Description = { en: readonly [string, string]; pl: readonly [string, string] };
export type CatalogueKind = "methods" | "attacks" | "metrics";

const methods: Record<string, Description> = {
  LSB_METHOD: {
    en: ["Hides one message bit in each audio sample with a very small numerical change.", "Replaces the least significant bit of the sample’s 32-bit floating-point representation. Decoding reads those bits in order. This implementation uses float bits, not integer PCM bits: conversion to PCM, lossy compression or even small signal processing changes can erase the message."],
    pl: ["Ukrywa jeden bit wiadomości w każdej próbce dźwięku, bardzo nieznacznie zmieniając jej wartość.", "Zastępuje najmniej znaczący bit 32-bitowej reprezentacji zmiennoprzecinkowej próbki. Dekoder odczytuje te bity po kolei. Ta implementacja operuje na bitach float, a nie całkowitoliczbowego PCM: konwersja do PCM, kompresja stratna lub drobne przetwarzanie sygnału mogą usunąć wiadomość."],
  },
  FBSMethod: {
    en: ["Adapts LSB capacity to foreground and background regions of the recording.", "Separates foreground from background, shuffles sample positions with a shared seed, then stores two float-representation bits per foreground sample and one per background sample. Decoding repeats the segmentation and ordering. Both sample precision and stable segmentation matter; format conversion or processing can break extraction."],
    pl: ["Dostosowuje pojemność LSB do fragmentów pierwszego planu i tła nagrania.", "Rozdziela pierwszy plan i tło, miesza pozycje próbek za pomocą wspólnego ziarna, a następnie zapisuje dwa bity reprezentacji float w próbce pierwszego planu i jeden w próbce tła. Dekoder powtarza segmentację i kolejność. Odczyt wymaga zachowania precyzji próbek oraz podziału sygnału; konwersja formatu lub przetwarzanie mogą go zaburzyć."],
  },
  PRIME_FACTOR_INTERPOLATE: {
    en: ["Stores a variable number of bits as small offsets from interpolated sample values.", "Every second sample is replaced by an interpolation of its retained neighbours plus the payload value. Capacity follows the least prime factor of a log-scaled neighbour difference, capped by max_bits_per_sample. The decoder derives the same prediction and capacity from the neighbours. More bits mean larger offsets; changing the neighbours can corrupt decoding."],
    pl: ["Zapisuje zmienną liczbę bitów jako niewielkie odchylenia od interpolowanych wartości próbek.", "Co druga próbka jest zastępowana interpolacją zachowanych sąsiadów powiększoną o wartość danych. Pojemność wynika z najmniejszego czynnika pierwszego logarytmicznie przeskalowanej różnicy sąsiadów i limitu max_bits_per_sample. Dekoder odtwarza tę samą predykcję oraz pojemność. Więcej bitów oznacza większe zmiany; modyfikacja sąsiadów może uszkodzić odczyt."],
  },
  DCT_DELTA_LSB_METHOD: {
    en: ["Encodes bits in the relative norms of two groups of cosine-transform coefficients.", "Transforms each frame with DCT, splits coefficients into two vectors and makes one norm larger than the other according to the bit. Decoding compares the norms. Despite the historical LSB name, this implementation modifies norm relations. delta_value sets the separation relative to the frame level; larger separation increases distortion and the decision margin."],
    pl: ["Koduje bity w relacji norm dwóch grup współczynników transformacji kosinusowej.", "Przekształca ramkę przez DCT, dzieli współczynniki na dwa wektory i zależnie od bitu zwiększa jedną normę względem drugiej. Dekoder porównuje normy. Mimo historycznej nazwy LSB implementacja zmienia relacje norm. delta_value ustala różnicę względem poziomu ramki; większa różnica zwiększa zniekształcenie i margines decyzji."],
  },
  DWT_LSB_METHOD: {
    en: ["Hides bits in the parity of quantised wavelet detail coefficients.", "A two-level discrete wavelet transform separates the signal into approximation and detail bands. Selected detail coefficients are quantised to even or odd indices and decoded by parity. step_scale controls the step relative to detail-band RMS, making it follow signal level. Filtering and requantisation can still move coefficients across decision boundaries."],
    pl: ["Ukrywa bity w parzystości skwantowanych współczynników detali falkowych.", "Dwupoziomowa dyskretna transformacja falkowa rozdziela sygnał na aproksymację i detale. Wybrane współczynniki detali są kwantowane do indeksów parzystych lub nieparzystych, z których dekoder odczytuje bity. step_scale określa krok względem RMS pasma detali, więc skaluje się on z poziomem sygnału. Filtracja i ponowna kwantyzacja mogą jednak zmienić decyzję dekodera."],
  },
  DCT_B1_METHOD: {
    en: ["Embeds a watermark in a selected DCT band using masking and energy compensation.", "Processes audio in frames, changes coefficient groups to represent bits, and compensates energy changes while reconstructing the waveform. The detector evaluates the corresponding coefficient relations. Frame and group lengths control capacity and the embedding region; preserving frame alignment is essential after temporal attacks."],
    pl: ["Osadza znak wodny w wybranym paśmie DCT, wykorzystując maskowanie i kompensację energii.", "Przetwarza dźwięk ramkami, zmienia grupy współczynników zgodnie z bitami i kompensuje zmiany energii podczas rekonstrukcji. Detektor ocenia odpowiednie relacje współczynników. Długości ramek i grup wpływają na pojemność oraz obszar osadzania; po atakach czasowych kluczowe jest zachowanie położenia ramek."],
  },
  NORM_SPACE_METHOD: {
    en: ["Represents each bit by which of two transform-domain vectors has the larger norm.", "Applies a Haar DWT and then DCT to the approximation band. Even and odd DCT coefficients form two vectors whose norms are separated by a relative delta. The decoder compares them without the original recording. Increasing delta strengthens the separation but changes audio more; cropping can break the segment grid."],
    pl: ["Reprezentuje bit przez wskazanie, który z dwóch wektorów w dziedzinie transformacji ma większą normę.", "Wykonuje DWT Haara, a następnie DCT pasma aproksymacji. Parzyste i nieparzyste współczynniki tworzą wektory, których normy rozsuwa względny parametr delta. Dekoder porównuje je bez oryginalnego nagrania. Większa delta wzmacnia różnicę kosztem większych zmian dźwięku; przycięcie może zaburzyć podział na segmenty."],
  },
  FSVC_METHOD: {
    en: ["Stores bits in the relative singular values of two frequency-domain frame halves.", "Splits each payload frame in half, applies DCT, selects coefficient bands and computes their singular values. Embedding enforces a bit-dependent ratio; decoding compares the values. In the current implementation the ratio is controlled by an internal alpha; the exposed delta parameter is stored but does not affect encoding. Temporal misalignment changes the compared halves."],
    pl: ["Zapisuje bity w relacji wartości singularnych dwóch połówek ramki w dziedzinie częstotliwości.", "Dzieli ramkę na pół, wykonuje DCT, wybiera pasma współczynników i oblicza wartości singularne. Osadzanie wymusza proporcję zależną od bitu, a dekoder porównuje wartości. W tej implementacji proporcją steruje wewnętrzna alpha; udostępniony parametr delta jest zapisywany, ale nie wpływa na kodowanie. Przesunięcie czasowe zmienia porównywane połówki."],
  },
  BLIND_SVD_METHOD: {
    en: ["Embeds one bit per frame in the largest singular value of an entropy-selected DCT sub-band.", "Chooses a low-frequency sub-band with maximum estimated entropy, reshapes it into a matrix and applies SVD. Quantisation parity of the largest singular value carries the bit. The step is derived from the remaining singular values and quantization_coefficient. No original cover is needed, but processing that changes sub-band selection can disrupt detection."],
    pl: ["Osadza jeden bit na ramkę w największej wartości singularnej podpasma DCT wybranego według entropii.", "Wybiera podpasmo niskich częstotliwości o największej oszacowanej entropii, układa je w macierz i wykonuje SVD. Bit jest zapisany w parzystości kwantyzacji największej wartości singularnej. Krok wynika z pozostałych wartości i quantization_coefficient. Oryginał nie jest potrzebny, ale przetwarzanie zmieniające wybór podpasma może zakłócić detekcję."],
  },
  LWT_METHOD: {
    en: ["Encodes bits as the sign of blocks of wavelet detail coefficients.", "This implementation uses a two-level Haar wavelet decomposition and groups eight detail coefficients per bit. It forces a positive or negative block with a minimum magnitude set by threshold, then reconstructs the signal. Decoding reads the sign of the block mean. A larger threshold creates a stronger mark and more distortion; alignment and detail-band preservation matter."],
    pl: ["Koduje bity jako znak bloków współczynników detali falkowych.", "Ta implementacja używa dwupoziomowej dekompozycji Haara i grupuje po osiem współczynników detali na bit. Wymusza dodatni lub ujemny blok z minimalną wartością bezwzględną threshold, po czym odtwarza sygnał. Dekoder odczytuje znak średniej bloku. Większy próg wzmacnia znak i zniekształcenia; istotne są synchronizacja oraz zachowanie pasma detali."],
  },
  WIRELESS_DWT_LSB_METHOD: {
    en: ["Places payload bits in the low-frequency approximation coefficients of a wavelet transform.", "Scales and rounds DWT approximation coefficients to integers, replaces up to lsb_depth low bits and reconstructs the waveform. Decoding repeats the transform and scaling. Wavelet type, level and coefficient_scale affect capacity and distortion. This adapts the paper’s carrier idea to direct bit payloads; the name does not imply guaranteed survival of a wireless channel."],
    pl: ["Umieszcza dane w niskoczęstotliwościowych współczynnikach aproksymacji transformacji falkowej.", "Skaluje i zaokrągla współczynniki aproksymacji DWT do liczb całkowitych, zastępuje do lsb_depth najmłodszych bitów i odtwarza sygnał. Dekoder powtarza transformację oraz skalowanie. Rodzaj falki, poziom i coefficient_scale wpływają na pojemność oraz zniekształcenia. Jest to adaptacja idei nośnika z publikacji do ciągu bitów; nazwa nie gwarantuje odporności na kanał bezprzewodowy."],
  },
  SYNC_DWT_DCT_METHOD: {
    en: ["Combines transform-domain data with synchronisation codes to locate marked blocks after timing changes.", "Writes a Barker-based sync pattern through quantised sample-group means, followed by payload quantisation in the DCT of a DWT approximation band. The decoder scans offsets and validates candidate blocks. Relative quantisation steps follow signal level. Coefficient selection and step rules are implementation choices; successful resynchronisation still depends on the attack and remaining audio."],
    pl: ["Łączy dane w dziedzinie transformacji z kodami synchronizacji, aby odnajdywać bloki po zmianach czasowych.", "Zapisuje wzorzec synchronizacji oparty na kodzie Barkera przez kwantyzację średnich grup próbek, a następnie dane w DCT pasma aproksymacji DWT. Dekoder przeszukuje przesunięcia i sprawdza kandydatów na bloki. Względne kroki kwantyzacji zależą od poziomu sygnału. Wybór współczynników i kroków jest decyzją implementacyjną; skuteczność synchronizacji zależy od ataku i zachowanego dźwięku."],
  },
  EMD_METHOD: {
    en: ["Encodes bits in extrema of a slow component obtained by empirical mode decomposition.", "Decomposes frames into oscillatory modes and quantises extrema of the remainder after the selected IMFs. It re-decomposes and corrects embedding in a closed loop; extrema vote on one bit per frame. This differs from marking only the last IMF in the paper. Filtering can change the decomposition itself, while repeated decomposition also increases computation cost."],
    pl: ["Koduje bity w ekstremach wolnozmiennej składowej uzyskanej przez empiryczną dekompozycję modów.", "Rozkłada ramki na składowe oscylacyjne i kwantuje ekstrema reszty po wydzieleniu wybranych IMF. Ponownie wykonuje dekompozycję i koryguje osadzanie w pętli; ekstrema głosują na jeden bit w ramce. To odstępstwo od osadzania wyłącznie w ostatnim IMF z publikacji. Filtracja może zmieniać sam rozkład, a wielokrotna dekompozycja zwiększa koszt obliczeń."],
  },
  DSSS_METHOD: {
    en: ["Spreads each bit over a frame using a key-derived pseudo-noise sequence.", "Adds a bipolar sequence with sign determined by the bit and amplitude proportional to local RMS and alpha. The receiver correlates the frame with the same sequence and reads the correlation sign. Spreading distributes the payload over many samples, but the cover itself interferes with detection. Larger alpha improves the detection margin at the cost of more added noise."],
    pl: ["Rozprasza każdy bit po ramce za pomocą sekwencji pseudolosowej wyprowadzonej z klucza.", "Dodaje sekwencję bipolarną ze znakiem zależnym od bitu i amplitudą proporcjonalną do lokalnego RMS oraz alpha. Odbiornik koreluje ramkę z tą samą sekwencją i odczytuje znak korelacji. Dane są rozłożone na wiele próbek, lecz sam nośnik zakłóca detekcję. Większa alpha zwiększa margines odczytu kosztem większego szumu."],
  },
  IMPROVED_SPREAD_SPECTRUM_METHOD: {
    en: ["Reduces host-signal interference before adding a spread-spectrum watermark.", "Projects each carrier frame onto a key-derived chip sequence and compensates its existing component before setting a bit-dependent projection. The decoder reads the correlation sign. This removes a source of ambiguity present in plain DSSS. strength controls the mark level; compensation itself also changes the carrier, and frame synchronisation is still required."],
    pl: ["Ogranicza zakłócenie pochodzące od nośnika przed dodaniem znaku o rozproszonym widmie.", "Rzutuje ramkę na sekwencję wyprowadzoną z klucza i kompensuje istniejącą składową, zanim ustali projekcję zależną od bitu. Dekoder odczytuje znak korelacji. Usuwa to źródło niejednoznaczności zwykłego DSSS. strength steruje poziomem znaku; sama kompensacja również zmienia nośnik, a synchronizacja ramek nadal jest potrzebna."],
  },
  ECHO_METHOD: {
    en: ["Represents zero and one by echoes with different delays.", "Splits the recording into payload frames and mixes in a delayed copy using alpha. The decoder detects the selected delay through cepstral analysis. Echo strength trades audibility against detection margin. Short frames, existing reverberation or temporal changes can make the two delay hypotheses difficult to distinguish."],
    pl: ["Reprezentuje zero i jedynkę przez echa o różnych opóźnieniach.", "Dzieli nagranie na ramki wiadomości i domiesza opóźnioną kopię z siłą alpha. Dekoder wykrywa wybrane opóźnienie przez analizę cepstralną. Siła echa wiąże słyszalność z marginesem detekcji. Krótkie ramki, istniejący pogłos lub zmiany czasowe mogą utrudnić odróżnienie obu opóźnień."],
  },
  BACKWARD_FORWARD_ECHO_METHOD: {
    en: ["Carries bits with paired backward and forward echoes.", "Uses echo kernels on both sides of a sample position with opposite signs. The detector compares the corresponding cepstral responses rather than relying on a single echo peak. alpha controls the added echo strength. The paired structure changes the detection statistic, but does not remove sensitivity to reverberation or lost frame alignment."],
    pl: ["Przenosi bity za pomocą par ech wstecznych i przednich.", "Używa jąder echa po obu stronach pozycji próbki z przeciwnymi znakami. Detektor porównuje odpowiadające im odpowiedzi cepstralne zamiast pojedynczego maksimum echa. alpha steruje siłą dodanego echa. Konstrukcja pary zmienia statystykę detekcji, ale nie eliminuje wrażliwości na pogłos i utratę synchronizacji ramek."],
  },
  TIME_SPREAD_ECHO_METHOD: {
    en: ["Distributes the echo watermark over multiple delays using a keyed sequence.", "A pseudo-noise kernel spreads echo energy in time instead of concentrating it at one delay. The decoder uses the corresponding sequence to detect the bit from the cepstral response. alpha sets strength and the shared seed reproduces the kernel. Spreading changes the audibility and detection trade-off; it still needs enough audio per bit and correct alignment."],
    pl: ["Rozkłada echo znaku wodnego na wiele opóźnień za pomocą sekwencji zależnej od klucza.", "Jądro pseudolosowe rozprasza energię echa w czasie zamiast skupiać ją w jednym opóźnieniu. Dekoder używa odpowiadającej sekwencji do odczytania bitu z odpowiedzi cepstralnej. alpha określa siłę, a wspólne ziarno odtwarza jądro. Rozpraszanie zmienia kompromis między słyszalnością a detekcją; nadal potrzeba odpowiedniej ilości dźwięku na bit i synchronizacji."],
  },
  PHASE_CODING_METHOD: {
    en: ["Stores the message in Fourier phases of the first audio block.", "Sets selected phases to +π/2 or −π/2 and mirrors them to preserve a real waveform. Subsequent blocks retain their original inter-block phase differences. Decoding reads the signs of the first block’s phases. Magnitudes are retained during embedding, but a shift or removal of the opening block can destroy access to the payload."],
    pl: ["Zapisuje wiadomość w fazach transformaty Fouriera pierwszego bloku dźwięku.", "Ustawia wybrane fazy na +π/2 lub −π/2 i odbija je symetrycznie, aby zachować rzeczywisty sygnał. Kolejne bloki zachowują pierwotne różnice faz między blokami. Dekoder odczytuje znaki faz pierwszego bloku. Moduły widma są zachowywane przy osadzaniu, lecz przesunięcie lub usunięcie początku może uniemożliwić odczyt danych."],
  },
  IMPROVED_PHASE_CODING_METHOD: {
    en: ["Distributes phase-coded message portions across multiple Fourier blocks.", "Divides the payload among segments and sets selected phase pairs to ±π/2 while retaining spectral magnitudes. The decoder reconstructs the segment layout from the message length and reads phase signs. Distribution avoids concentrating all bits in the first segment, but it is not error correction; altered length, phase distortion and trimming can still corrupt bits."],
    pl: ["Rozdziela fragmenty wiadomości kodowanej fazowo pomiędzy wiele bloków Fouriera.", "Dzieli dane między segmenty i ustawia wybrane pary faz na ±π/2, zachowując moduły widma. Dekoder odtwarza układ segmentów z długości wiadomości i odczytuje znaki faz. Rozłożenie bitów nie jest kodem korekcyjnym; zmiana długości, zniekształcenia fazowe i przycinanie nadal mogą uszkodzić dane."],
  },
  QIM_METHOD: {
    en: ["Encodes bits by choosing between two quantisation grids for a keyed frame projection.", "Projects a frame onto a key-derived direction and moves that projection to the nearest point on the bit’s dithered grid. The decoder chooses the closer grid. The step follows energy orthogonal to the projection, which embedding leaves unchanged, and is scaled by step_scale. Larger steps increase separation and distortion; timing changes disrupt the frame projections."],
    pl: ["Koduje bity przez wybór jednej z dwóch siatek kwantyzacji projekcji ramki zależnej od klucza.", "Rzutuje ramkę na kierunek wyprowadzony z klucza i przesuwa projekcję do najbliższego punktu siatki danego bitu. Dekoder wybiera bliższą siatkę. Krok zależy od energii prostopadłej do projekcji, niezmienianej przez osadzanie, oraz step_scale. Większy krok zwiększa rozdzielenie i zniekształcenia; zmiany czasowe zaburzają projekcje ramek."],
  },
  PATCHWORK_MULTILAYER_METHOD: {
    en: ["Carries bits in statistical differences between paired DCT coefficient groups.", "Reorders coefficients in a selected band and adjusts the mean absolute values of paired segments so their ordering represents a bit. Extraction compares these means. Despite the multilayer name, the current code implements only the first layer. min_segment_length limits capacity; band removal and changes to the global transform grid can damage the mark."],
    pl: ["Przenosi bity w różnicach statystycznych między parami grup współczynników DCT.", "Zmienia kolejność współczynników wybranego pasma i dostosowuje średnie wartości bezwzględne par segmentów tak, by ich relacja oznaczała bit. Dekoder porównuje średnie. Mimo nazwy multilayer obecny kod implementuje tylko pierwszą warstwę. min_segment_length ogranicza pojemność; usunięcie pasma i zmiany globalnej siatki transformacji mogą uszkodzić znak."],
  },
  HISTOGRAM_METHOD: {
    en: ["Stores bits in the distribution of sample amplitudes rather than their positions.", "Forms an amplitude histogram and modifies population relations in groups of three neighbouring bins. The histogram range is relative to mean absolute amplitude; threshold controls the required relation. Because sample order is not used, the method targets timing and cropping robustness. Changes that reshape amplitude statistics, such as clipping or noise, can still destroy the relation."],
    pl: ["Zapisuje bity w rozkładzie amplitud próbek zamiast w ich pozycjach.", "Buduje histogram amplitud i zmienia relacje liczności w grupach trzech sąsiednich przedziałów. Zakres histogramu zależy od średniej amplitudy bezwzględnej, a threshold określa wymaganą relację. Brak zależności od kolejności próbek służy odporności na zmiany czasowe i przycięcie. Zmiany statystyk amplitudy, np. clipping lub szum, mogą jednak zniszczyć tę relację."],
  },
  LOW_FREQUENCY_AMPLITUDE_METHOD: {
    en: ["Encodes bits through amplitude relations between three low-frequency sub-segments.", "Separates low-frequency content and scales consecutive sub-segments so the middle amplitude lies above or below the average of its neighbours. The decoder reads that relation without the original. margin controls the separation. Relative amplitudes tolerate common gain changes, but high-pass filtering and temporal misalignment can remove or rearrange the carrier."],
    pl: ["Koduje bity przez relacje amplitud trzech podsegmentów niskoczęstotliwościowych.", "Wydziela niskie częstotliwości i skaluje kolejne podsegmenty tak, aby amplituda środkowego była powyżej lub poniżej średniej sąsiadów. Dekoder odczytuje relację bez oryginału. margin ustala rozdzielenie. Względne amplitudy tolerują wspólną zmianę głośności, lecz filtr górnoprzepustowy i przesunięcie czasowe mogą usunąć lub przestawić nośnik."],
  },
  AAC_STC_METHOD: {
    en: ["Chooses low-cost sample edits using perceptual codec residuals and syndrome-trellis coding.", "Converts audio to 16-bit PCM and estimates embedding costs from the difference after an AAC round trip, with Vorbis as a fallback. A trellis search selects inexpensive ±1 changes whose LSB syndrome encodes the message. Decoding applies the same parity-check matrix. The codec guides where to embed; it does not make the resulting LSB payload inherently resistant to transcoding."],
    pl: ["Wybiera zmiany próbek o małym koszcie, korzystając z reszty kodeka percepcyjnego i kodowania syndrome-trellis.", "Konwertuje dźwięk do PCM 16-bit i szacuje koszty osadzania z różnicy po kodowaniu i dekodowaniu AAC, awaryjnie Vorbis. Przeszukiwanie kraty wybiera tanie zmiany ±1, których syndrom LSB koduje wiadomość. Dekoder stosuje tę samą macierz kontroli parzystości. Kodek wskazuje miejsce osadzania; nie zapewnia odporności powstałych danych LSB na transkodowanie."],
  },
  REVERSIBLE_PEE_METHOD: {
    en: ["Hides data while allowing exact recovery of the original 16-bit PCM cover when no damage occurs.", "Predicts each sample from its two predecessors and expands small prediction errors as 2e + bit; larger errors are shifted. A location map handles overflow risks and decoding reverses the mappings. threshold controls eligible errors and capacity. Reversibility refers to the cover rounded onto the 16-bit grid; processing or another bit-depth conversion can destroy both payload and restoration."],
    pl: ["Ukrywa dane, umożliwiając dokładne odzyskanie oryginalnego nośnika PCM 16-bit, jeśli nie został uszkodzony.", "Przewiduje próbkę na podstawie dwóch poprzednich i rozszerza małe błędy predykcji jako 2e + bit; większe błędy przesuwa. Mapa pozycji obsługuje ryzyko przepełnienia, a dekoder odwraca przekształcenia. threshold steruje wyborem błędów i pojemnością. Odwracalność dotyczy nośnika zaokrąglonego do siatki 16-bit; przetwarzanie lub zmiana głębi może zniszczyć dane i możliwość rekonstrukcji."],
  },
  LEARNABLE_EMBEDDING_GA_METHOD: {
    en: ["Provides an experimental embedding pipeline inspired by learnable watermarking and genetic optimisation.", "Maps bits to an upscaled waveform, applies a mask and adds a scaled residual; extraction uses correlation-style pooling. Without the paper’s trained weights, this implementation uses deterministic minimal operators and an all-ones mask. embedding_strength sets the residual level. Treat it as an implementation-specific baseline, not a reproduction of the trained network’s reported performance."],
    pl: ["Udostępnia eksperymentalny schemat inspirowany uczonym osadzaniem i optymalizacją genetyczną.", "Mapuje bity na rozciągnięty przebieg, stosuje maskę i dodaje przeskalowany sygnał; odczyt wykorzystuje agregację opartą na korelacji. Bez wytrenowanych wag z publikacji implementacja używa minimalnych operatorów deterministycznych i maski z samych jedynek. embedding_strength ustala siłę dodawanego sygnału. To wariant porównawczy właściwy tej implementacji, a nie odtworzenie wyników wytrenowanej sieci."],
  },
  FGAS_METHOD: {
    en: ["Optimises a small audio perturbation so a fixed neural decoder outputs the desired bits.", "Builds a deterministically initialised 1D convolutional decoder from a shared seed and optimises the input perturbation against the target message. The receiver reconstructs that decoder and thresholds its output. epsilon bounds the perturbation; optimisation settings affect cost and success. A small perturbation does not by itself guarantee robustness to codecs or resistance to steganalysis."],
    pl: ["Optymalizuje małe zaburzenie dźwięku tak, aby stały dekoder neuronowy zwrócił zadane bity.", "Buduje deterministycznie inicjalizowany dekoder konwolucyjny 1D ze wspólnego ziarna i optymalizuje zaburzenie wejścia względem wiadomości. Odbiornik odtwarza dekoder i progowo odczytuje wynik. epsilon ogranicza zaburzenie; ustawienia optymalizacji wpływają na koszt i powodzenie. Mała zmiana nie gwarantuje odporności na kodeki ani niewykrywalności przez steganalizę."],
  },
  AUDIOSEAL_METHOD: {
    en: ["Uses pretrained AudioSeal networks to generate and detect a neural audio watermark.", "Wraps the optional AudioSeal package and released model weights. The generator carries 16 bits per chunk, so longer messages are split across consecutive chunks; alpha scales the watermark contribution. Detection uses the corresponding neural model. Dependencies and weights must be available, and robustness should be measured for the actual audio and attack settings."],
    pl: ["Wykorzystuje wytrenowane sieci AudioSeal do generowania i wykrywania neuronowego znaku wodnego.", "Korzysta z opcjonalnego pakietu AudioSeal i opublikowanych wag modelu. Generator przenosi 16 bitów na fragment, więc dłuższe wiadomości są dzielone między kolejne fragmenty; alpha skaluje wkład znaku. Detekcja używa odpowiadającej sieci. Wymagane są zależności i wagi, a odporność należy mierzyć dla konkretnych nagrań oraz ustawień ataków."],
  },
  WAVMARK_METHOD: {
    en: ["Uses the pretrained WavMark neural model to embed and recover bit payloads in audio chunks.", "A one-second model window carries 32 bits: 16 synchronisation bits and 16 payload bits. The decoder searches for the sync pattern; this adapter uses 16 kHz audio and defaults to chunks of at least two seconds to leave search space. Longer messages use consecutive chunks. The package and weights are optional dependencies; robustness depends on the model and evaluated channel."],
    pl: ["Używa wytrenowanego modelu neuronowego WavMark do osadzania i odczytu bitów we fragmentach dźwięku.", "Jednosekundowe okno modelu przenosi 32 bity: 16 synchronizacji i 16 wiadomości. Dekoder szuka wzorca synchronizacji; adapter używa dźwięku 16 kHz i domyślnie co najmniej dwusekundowych fragmentów, zostawiając miejsce na przeszukiwanie. Dłuższe dane zajmują kolejne fragmenty. Pakiet i wagi są opcjonalnymi zależnościami; odporność zależy od modelu oraz badanego kanału."],
  },
};

const codecDescription = (codec: string): Description => ({
  en: [`Tests whether the message survives real ${codec} lossy encoding and decoding.`, "Runs the codec through FFmpeg and returns decoded PCM. bitrate_kbps sets the target bitrate; a lower rate usually discards more information. Optional delay alignment and length restoration separate codec damage from timing changes. Perceptual compression can remove quiet embedded components; results depend on the encoder and FFmpeg build."],
  pl: [`Sprawdza, czy wiadomość przetrwa rzeczywiste kodowanie i dekodowanie stratne ${codec}.`, "Uruchamia kodek przez FFmpeg i zwraca zdekodowany PCM. bitrate_kbps ustala docelową przepływność; niższa zwykle oznacza większą utratę informacji. Opcjonalne wyrównanie opóźnienia i przywrócenie długości oddzielają uszkodzenia kodeka od zmian czasowych. Kompresja percepcyjna może usuwać ciche składowe znaku; wynik zależy od enkodera i wersji FFmpeg."],
});

const attacks: Record<string, Description> = {
  codec: codecDescription("MP3 / AAC / Opus / Vorbis"),
  mp3: codecDescription("MP3"),
  aac: codecDescription("AAC"),
  opus: codecDescription("Opus"),
  vorbis: codecDescription("Vorbis"),
  awgn: {
    en: ["Adds white Gaussian noise to model a noisy recording or transmission channel.", "Measures signal power and scales random noise to the requested snr_db. Lower SNR means stronger noise, while seed reproduces the random sequence. Noise perturbs sample values and transform coefficients throughout the recording; the resulting bit errors reveal the detector’s tolerance to distributed disturbance."],
    pl: ["Dodaje biały szum gaussowski, symulując zaszumione nagranie lub kanał transmisyjny.", "Mierzy moc sygnału i skaluje losowy szum do zadanego snr_db. Niższy SNR oznacza silniejszy szum, a seed pozwala odtworzyć sekwencję. Szum zmienia wartości próbek i współczynniki transformacji w całym nagraniu; błędy bitowe pokazują tolerancję dekodera na rozproszone zakłócenie."],
  },
  pink_noise: {
    en: ["Adds pink noise, concentrating more disturbance at low frequencies than white noise.", "Generates noise with an approximately 1/f power spectrum and scales it to the requested SNR. snr_db controls total power and seed controls reproducibility. At equal SNR, its frequency distribution differs from AWGN, so comparing them helps identify whether the payload depends on low-frequency content."],
    pl: ["Dodaje szum różowy, skupiający więcej zakłóceń w niskich częstotliwościach niż szum biały.", "Generuje szum o widmie mocy zbliżonym do 1/f i skaluje go do zadanego SNR. snr_db steruje mocą, a seed powtarzalnością. Przy równym SNR rozkład częstotliwości różni się od AWGN, więc porównanie pokazuje zależność danych od niskich częstotliwości."],
  },
  impulse_noise: {
    en: ["Injects sparse strong impulses, resembling clicks or isolated transmission errors.", "Randomly selects a fraction of samples using density and sets impulse power from snr_db. At fixed total noise power, fewer affected samples mean stronger individual impulses. seed reproduces their positions. This distinguishes vulnerability to local damage from sensitivity to continuous background noise."],
    pl: ["Dodaje rzadkie silne impulsy przypominające trzaski lub pojedyncze błędy transmisji.", "Losowo wybiera część próbek według density i ustala moc impulsów przez snr_db. Przy stałej mocy zakłócenia mniej trafionych próbek oznacza silniejsze pojedyncze impulsy. seed odtwarza ich pozycje. Atak pozwala odróżnić podatność na lokalne uszkodzenia od wrażliwości na ciągły szum."],
  },
  low_pass: {
    en: ["Attenuates high frequencies to test whether the watermark depends on the upper band.", "Uses a Butterworth low-pass filter specified by cutoff and order. The default forward-backward mode avoids group delay but applies filtering twice; causal mode also changes phase. Lower cutoff removes more bandwidth. Lost upper-band payload components cannot be recovered merely by restoring the original sample rate."],
    pl: ["Tłumi wysokie częstotliwości, sprawdzając zależność znaku od górnego pasma.", "Stosuje filtr dolnoprzepustowy Butterwortha określony częstotliwością odcięcia i rzędem. Domyślny przebieg w przód i wstecz usuwa opóźnienie grupowe, ale filtruje dwukrotnie; wariant przyczynowy zmienia także fazę. Niższe odcięcie usuwa więcej pasma. Przywrócenie częstotliwości próbkowania nie odtwarza utraconych składowych danych."],
  },
  high_pass: {
    en: ["Attenuates low frequencies, as in rumble removal or an AC-coupled recording path.", "Applies a Butterworth high-pass filter with a chosen cutoff and order. Raising the cutoff removes more low-band content and can damage amplitude-relation or low-frequency transform embedding. zero_phase controls forward-backward versus causal filtering, separating band attenuation from phase-delay effects."],
    pl: ["Tłumi niskie częstotliwości, podobnie do usuwania dudnienia lub toru bez składowej stałej.", "Stosuje filtr górnoprzepustowy Butterwortha o wybranym odcięciu i rzędzie. Podniesienie odcięcia usuwa więcej niskiego pasma i może niszczyć osadzanie oparte na relacjach amplitud lub niskich częstotliwościach. zero_phase wybiera filtrację w przód i wstecz albo przyczynową, rozdzielając tłumienie pasma od efektów opóźnienia fazowego."],
  },
  band_pass: {
    en: ["Keeps only a selected frequency band, modelling a bandwidth-limited channel.", "Combines lower and upper cutoffs in a Butterworth band-pass filter. Narrowing the passband removes more carrier information, as in telephone-like transmission. Filter order controls transition steepness and zero_phase controls phase handling. Payload stored outside the retained band is especially exposed."],
    pl: ["Przepuszcza tylko wybrane pasmo częstotliwości, modelując kanał o ograniczonej szerokości pasma.", "Łączy dolne i górne odcięcie w filtrze pasmowoprzepustowym Butterwortha. Zwężenie pasma usuwa więcej informacji nośnika, jak w transmisji telefonicznej. Rząd określa stromość zboczy, a zero_phase sposób obsługi fazy. Szczególnie narażone są dane zapisane poza zachowanym pasmem."],
  },
  notch: {
    en: ["Suppresses a narrow frequency region, such as hum or a tonal interferer.", "Uses a second-order IIR notch around a centre frequency; its quality factor determines bandwidth. Optional depth_db allows partial attenuation instead of a full notch. It probes whether a mark relies on a narrow carrier region rather than broadly distributed energy."],
    pl: ["Wycisza wąski zakres częstotliwości, np. przydźwięk lub zakłócenie tonalne.", "Używa filtra zaporowego IIR drugiego rzędu wokół częstotliwości środkowej; dobroć określa szerokość pasma. Opcjonalny depth_db pozwala na częściowe tłumienie zamiast pełnej zapory. Sprawdza, czy znak zależy od wąskiego obszaru widma, czy od szerzej rozłożonej energii."],
  },
  smoothing: {
    en: ["Smooths samples by replacing them with local moving averages.", "Convolves the waveform with a uniform boxcar window. A longer window suppresses fast variations more strongly and produces spectral nulls related to the window length. This models simple smoothing or naive denoising and can erase fine sample-level payload changes."],
    pl: ["Wygładza próbki przez zastępowanie ich lokalnymi średnimi ruchomymi.", "Wykonuje splot przebiegu z równomiernym oknem prostokątnym. Dłuższe okno mocniej tłumi szybkie zmiany i wprowadza zera widma zależne od długości okna. Modeluje proste wygładzanie lub naiwne odszumianie i może usuwać drobne zmiany próbek niosące wiadomość."],
  },
  resample: {
    en: ["Converts to an intermediate sample rate and back to test rate-conversion damage.", "Uses polyphase FIR resampling with anti-alias filtering. A lower intermediate_hz limits the recoverable bandwidth and changes the sample grid. Optional restore_length trims or pads rounding differences. Returning to the original rate lets the decoder use its expected rate, but does not restore discarded frequencies or original sample values."],
    pl: ["Zmienia częstotliwość próbkowania na pośrednią i z powrotem, badając skutki konwersji.", "Używa wielofazowego resamplingu FIR z filtracją antyaliasingową. Niższy intermediate_hz ogranicza zachowane pasmo i zmienia siatkę próbek. Opcjonalny restore_length przycina lub uzupełnia różnice zaokrągleń. Powrót do pierwotnej częstotliwości daje dekoderowi oczekiwany format, ale nie odtwarza odrzuconych częstotliwości ani wartości próbek."],
  },
  clock_drift: {
    en: ["Simulates a small mismatch between playback and recording clocks.", "Resamples by a factor derived from offset_ppm while leaving the nominal sample rate unchanged. Even a small mismatch accumulates into positional drift over a long recording. The attack tests whether a decoder can track a gradually changing sample grid, not simply a constant initial offset."],
    pl: ["Symuluje małą różnicę zegarów urządzenia odtwarzającego i nagrywającego.", "Próbkuje ponownie ze współczynnikiem wynikającym z offset_ppm, pozostawiając nominalną częstotliwość bez zmian. Nawet mała różnica narasta do zauważalnego przesunięcia próbek w długim nagraniu. Atak sprawdza śledzenie stopniowo zmieniającej się siatki, a nie tylko stałego przesunięcia początku."],
  },
  bit_depth: {
    en: ["Requantises audio to fewer PCM amplitude levels.", "Maps samples to a uniform grid with spacing 2 / 2^bits over nominal full scale. The mode selects a grid with or without an exact zero level; optional TPDF dither adds noise before quantisation. Lower bit depth removes finer sample detail and is particularly destructive to payloads stored in low sample bits."],
    pl: ["Ponownie kwantuje dźwięk do mniejszej liczby poziomów amplitudy PCM.", "Przypisuje próbki do równomiernej siatki o odstępie 2 / 2^bits w nominalnym zakresie. Tryb wybiera siatkę z dokładnym poziomem zera lub bez niego; opcjonalny dither TPDF dodaje szum przed kwantyzacją. Mniejsza głębia usuwa drobniejsze szczegóły i szczególnie niszczy dane zapisane w najmłodszych bitach próbek."],
  },
  gain: {
    en: ["Changes playback level to test dependence on absolute amplitude.", "Multiplies samples by the gain corresponding to the requested decibel change. Optional clipping limits values that exceed full scale and adds a separate nonlinear distortion. Pure gain leaves relative amplitude relations intact, whereas fixed absolute detection thresholds or quantisation steps may no longer match."],
    pl: ["Zmienia głośność, sprawdzając zależność dekodera od bezwzględnej amplitudy.", "Mnoży próbki przez wzmocnienie odpowiadające zmianie w decybelach. Opcjonalne ograniczanie obcina wartości poza pełną skalą i dodaje nieliniowe zniekształcenie. Czyste wzmocnienie zachowuje względne relacje amplitud, ale stałe progi detekcji lub bezwzględne kroki kwantyzacji mogą przestać pasować."],
  },
  clipping: {
    en: ["Limits signal peaks, modelling saturation or overdriven audio.", "Hard-clips samples at a threshold expressed relative to full scale, the signal peak or an amplitude percentile. A lower threshold affects more samples and reshapes the waveform, introducing additional spectral components. This tests payloads stored in peak values, amplitude statistics and transform coefficients without deliberately changing the time axis."],
    pl: ["Ogranicza szczyty sygnału, modelując nasycenie lub przesterowanie dźwięku.", "Twardo obcina próbki na progu określonym względem pełnej skali, szczytu sygnału lub percentyla amplitudy. Niższy próg obejmuje więcej próbek i zmienia przebieg, tworząc dodatkowe składowe widma. Bada dane zapisane w szczytach, statystykach amplitudy i współczynnikach transformacji bez celowej zmiany osi czasu."],
  },
  compression_dynamic: {
    en: ["Reduces differences between loud and quiet passages through dynamic gain control.", "An envelope follower drives gain reduction above a threshold using the configured ratio, attack and release times. Unlike file compression, this operates directly on waveform amplitude. Gain varies over time, so relations between distant segments can change even when constant-volume scaling would leave them intact."],
    pl: ["Zmniejsza różnice między głośnymi i cichymi fragmentami przez dynamiczną regulację wzmocnienia.", "Śledzenie obwiedni steruje redukcją wzmocnienia powyżej progu zgodnie ze współczynnikiem kompresji oraz czasami attack i release. To kompresja dynamiki, a nie rozmiaru pliku. Wzmocnienie zmienia się w czasie, więc relacje odległych segmentów mogą się zmienić, mimo że stała zmiana głośności by je zachowała."],
  },
  time_shift: {
    en: ["Moves the recording in time to test decoder synchronisation.", "Uses shift_samples or shift_ms to delay or advance audio. Pad mode fills exposed positions with zeros while keeping length; circular mode wraps samples around. A small shift can move every decoding frame away from its embedded position even when much of the waveform itself is unchanged."],
    pl: ["Przesuwa nagranie w czasie, sprawdzając synchronizację dekodera.", "Używa shift_samples lub shift_ms do opóźnienia albo przyspieszenia sygnału. Tryb pad uzupełnia odsłonięte pozycje zerami przy zachowaniu długości; circular przenosi próbki na drugi koniec. Małe przesunięcie może przestawić każdą ramkę odczytu, nawet jeśli większość przebiegu pozostaje niezmieniona."],
  },
  crop: {
    en: ["Removes part of the recording to test payload loss and framing sensitivity.", "Deletes the configured fraction from the start, end, both ends or a seeded random location. The result is shorter, so some bits may disappear and length-derived frame boundaries may move. It tests partial-recording recovery; success depends on redundancy, synchronisation and where the method stored its message."],
    pl: ["Usuwa część nagrania, badając utratę danych i wrażliwość podziału na ramki.", "Wycina zadaną część z początku, końca, obu końców lub losowego miejsca ustalanego ziarnem. Wynik jest krótszy, więc część bitów może zniknąć, a granice ramek wyznaczane z długości mogą się przesunąć. Sprawdza odczyt z fragmentu nagrania; powodzenie zależy od nadmiarowości, synchronizacji i miejsca zapisu wiadomości."],
  },
  zero_padding: {
    en: ["Adds silence before or after audio without deliberately changing the retained samples.", "Prepends and optionally appends zero-valued samples according to the configured durations. Leading silence shifts every embedded position; trailing silence can alter framing based on total duration. This isolates sensitivity to container padding or edited clip boundaries from direct damage to the original waveform."],
    pl: ["Dodaje ciszę przed dźwiękiem lub za nim bez celowej zmiany zachowanych próbek.", "Dopisuje próbki zerowe na początku i opcjonalnie na końcu według zadanych czasów. Cisza na początku przesuwa pozycje danych; cisza na końcu może zmienić ramkowanie oparte na całkowitej długości. Oddziela wrażliwość na dopełnienie kontenera lub granice montażu od bezpośredniego uszkodzenia przebiegu."],
  },
  sample_jitter: {
    en: ["Inserts or deletes short sample runs at scattered positions.", "Deletion removes samples; insertion repeats preceding samples to model a simple concealment operation. Seeded positions make the attack reproducible. Each edit shifts subsequent boundaries, creating local and cumulative desynchronisation that a single global offset correction cannot necessarily repair."],
    pl: ["Wstawia lub usuwa krótkie serie próbek w rozproszonych miejscach.", "Usuwanie wycina próbki, a wstawianie powtarza poprzednią próbkę, modelując proste maskowanie braków. Pozycje ustalane ziarnem zapewniają powtarzalność. Każda zmiana przesuwa kolejne granice, tworząc lokalną i narastającą desynchronizację, której nie musi naprawić jedno globalne przesunięcie."],
  },
  dropout: {
    en: ["Replaces short audio regions with zeros, modelling missing packets or recording dropouts.", "Selects runs of samples and silences them while preserving total length. Parameters determine how much audio is lost and the run size; seed reproduces placement. Unlike cropping, positions after a dropout remain aligned, helping distinguish loss of payload content from loss of synchronisation."],
    pl: ["Zastępuje krótkie obszary zerami, modelując utracone pakiety lub przerwy w nagraniu.", "Wybiera serie próbek i wycisza je, zachowując całkowitą długość. Parametry określają ilość traconego dźwięku i rozmiar serii, a seed odtwarza pozycje. W przeciwieństwie do przycięcia późniejsze próbki pozostają wyrównane, co pomaga odróżnić utratę treści danych od utraty synchronizacji."],
  },
  time_stretch: {
    en: ["Changes duration while approximately preserving pitch.", "Uses a phase vocoder to resynthesise audio at a different tempo. This changes both the temporal grid and waveform phases, rather than merely moving existing samples. The rate controls the duration change. It can damage phase-based and frame-based payloads even when the tempo difference sounds small."],
    pl: ["Zmienia czas trwania przy przybliżonym zachowaniu wysokości dźwięku.", "Używa wokodera fazowego do ponownej syntezy w innym tempie. Zmienia zarówno siatkę czasową, jak i fazy przebiegu, zamiast tylko przestawiać próbki. Współczynnik tempa ustala zmianę długości. Może uszkadzać dane fazowe i ramkowe nawet przy mało słyszalnej różnicy tempa."],
  },
  speed: {
    en: ["Changes playback speed, affecting both duration and pitch.", "Resamples the waveform to model faster or slower playback while keeping the nominal output rate. Faster playback shortens the clip and raises pitch; slower playback does the reverse. It probes timing and frequency dependence together, unlike time stretching, which aims to preserve pitch."],
    pl: ["Zmienia prędkość odtwarzania, wpływając jednocześnie na długość i wysokość dźwięku.", "Próbkuje przebieg ponownie, modelując szybsze lub wolniejsze odtwarzanie przy zachowaniu nominalnej częstotliwości wyjściowej. Szybsze odtwarzanie skraca nagranie i podnosi wysokość, a wolniejsze działa odwrotnie. Bada jednocześnie zależność czasową i częstotliwościową, inaczej niż zmiana tempa z zachowaniem wysokości."],
  },
  pitch_shift: {
    en: ["Raises or lowers pitch while keeping approximately the same duration.", "Applies a pitch-shifting operation parameterised in semitones. The resynthesis changes frequency content and phase relationships even though the overall duration is maintained. It tests whether embedding relies on particular spectral positions or waveform detail, rather than simply on clip length."],
    pl: ["Podnosi lub obniża wysokość dźwięku przy zachowaniu przybliżonej długości.", "Stosuje zmianę wysokości określoną w półtonach. Ponowna synteza zmienia zawartość częstotliwościową i relacje faz mimo zachowania czasu trwania. Sprawdza, czy osadzanie zależy od konkretnych pozycji widma lub szczegółów przebiegu, a nie tylko od długości nagrania."],
  },
  echo: {
    en: ["Adds delayed signal copies to model discrete acoustic reflections.", "Mixes the original with echoes whose delays and decaying amplitudes are configurable. Reflections change the spectrum and cepstral structure, potentially masking or imitating echo-hiding cues. Delay determines reflection spacing and decay controls strength; tail handling can also affect the output length."],
    pl: ["Dodaje opóźnione kopie sygnału, modelując pojedyncze odbicia akustyczne.", "Miesza oryginał z echami o konfigurowalnych opóźnieniach i malejących amplitudach. Odbicia zmieniają widmo i strukturę cepstralną, mogąc maskować lub naśladować ślady ukrywania w echu. Opóźnienie określa odstęp odbić, a zanikanie ich siłę; obsługa ogona może też zmienić długość wyniku."],
  },
  reverb: {
    en: ["Simulates reverberation by convolving audio with a generated room impulse response.", "Combines direct sound with a decaying reflection response controlled by reverberation and mixing parameters. The random response is reproducible with a seed. Reverberation smears energy over time and changes phase, stressing echo detectors and local frame statistics. This is a simulated room, not a measured playback-and-recording experiment."],
    pl: ["Symuluje pogłos przez splot dźwięku z wygenerowaną odpowiedzią impulsową pomieszczenia.", "Łączy dźwięk bezpośredni z zanikającą odpowiedzią odbić sterowaną parametrami pogłosu i mieszania. Losową odpowiedź można odtworzyć przez seed. Pogłos rozmywa energię w czasie i zmienia fazę, obciążając detektory echa oraz lokalne statystyki ramek. To symulacja pomieszczenia, a nie pomiar rzeczywistego odtwarzania i nagrywania."],
  },
  acoustic_channel: {
    en: ["Combines several effects to approximate a loudspeaker-to-microphone channel.", "Chains acoustic and transmission effects such as bandwidth limitation, reverberation, noise and clock mismatch according to its parameters. Damage accumulates across stages, so surviving each effect separately does not establish survival of the combination. It is a reproducible synthetic channel and does not replace validation on real recording hardware."],
    pl: ["Łączy kilka efektów, przybliżając kanał od głośnika do mikrofonu.", "Stosuje kolejno efekty akustyczne i transmisyjne, takie jak ograniczenie pasma, pogłos, szum i różnica zegarów, zgodnie z parametrami. Uszkodzenia nakładają się, więc odporność na każdy efekt osobno nie dowodzi odporności na ich połączenie. To powtarzalny kanał syntetyczny, który nie zastępuje sprawdzenia na rzeczywistym sprzęcie."],
  },
};
const metrics: Record<string, Description> = {
  SNR_METRIC: {
    en: ["Measures waveform fidelity as the ratio of original signal energy to error energy.", "Computes 10 log10 of reference energy divided by the energy of the samplewise difference. Higher dB means less error relative to the reference. Requires aligned signals and penalises gain or time shifts strongly. It measures numerical fidelity, not perceived quality, message recovery or steganographic detectability."],
    pl: ["Mierzy wierność przebiegu jako stosunek energii oryginału do energii błędu.", "Oblicza 10 log10 ilorazu energii odniesienia i energii różnicy próbek. Więcej dB oznacza mniejszy błąd względem oryginału. Wymaga wyrównanych sygnałów i silnie karze zmianę wzmocnienia lub przesunięcie. Mierzy zgodność liczbową, a nie jakość słuchową, odczyt wiadomości czy wykrywalność steganografii."],
  },
  SNR_SEG_METRIC: {
    en: ["Averages signal-to-noise ratios over short speech frames.", "Calculates a local energy-to-error ratio for each frame, limits extreme frame scores and averages them. This gives quieter sections more influence than a single global SNR. Higher dB is better. Frame length, silence and alignment affect the result; it remains an error-energy measure rather than a listening score."],
    pl: ["Uśrednia stosunek sygnału do szumu w krótkich ramkach mowy.", "Oblicza lokalny stosunek energii sygnału do błędu, ogranicza skrajne wyniki ramek i uśrednia je. Cichsze fragmenty mają większy wpływ niż w globalnym SNR. Więcej dB oznacza lepszy wynik. Długość ramek, cisza i wyrównanie wpływają na ocenę; nadal jest to miara energii błędu, a nie ocena odsłuchowa."],
  },
  FWSNR_SEG_METRIC: {
    en: ["Measures segmental SNR with frequency-band weighting relevant to speech.", "Separates short-time spectra into perceptual bands, computes bandwise signal-to-error ratios and combines them with frequency-dependent weights. Higher scores indicate less weighted distortion. It can distinguish errors with similar total energy but different spectral locations; it requires a reference and temporal alignment."],
    pl: ["Mierzy segmentowy SNR z ważeniem pasm częstotliwości istotnych dla mowy.", "Rozdziela widma krótkoczasowe na pasma percepcyjne, oblicza stosunki sygnału do błędu w pasmach i łączy je wagami częstotliwościowymi. Wyższy wynik oznacza mniejsze ważone zniekształcenie. Rozróżnia błędy o podobnej energii, lecz innym położeniu widmowym; wymaga oryginału i wyrównania czasowego."],
  },
  PESQ_METRIC: {
    en: ["Predicts perceived speech quality by comparing degraded speech with its reference.", "Uses the PESQ perceptual model to align and compare auditory representations, combining disturbance measures into MOS-LQO. Higher is better; the catalogue reports the wideband scale up to about 4.64. The implementation depends on the PESQ library and supported speech sample rates. It is a speech-quality estimate, not a general music metric or a bit-error measure."],
    pl: ["Przewiduje postrzeganą jakość mowy przez porównanie zniekształconego sygnału z oryginałem.", "Model percepcyjny PESQ wyrównuje i porównuje reprezentacje słuchowe, łącząc miary zakłóceń w MOS-LQO. Wyższy wynik jest lepszy; katalog podaje skalę szerokopasmową do około 4,64. Implementacja zależy od biblioteki PESQ i obsługiwanych częstotliwości mowy. To estymacja jakości mowy, a nie ogólna miara muzyki ani błędów bitowych."],
  },
  VISQOL_METRIC: {
    en: ["Estimates perceived audio quality from similarity between reference and processed spectrograms.", "Uses official Google ViSQOL bindings and the audio-mode SVR model, with both inputs polyphase-resampled to 48 kHz. Spectro-temporal similarity is mapped to MOS-LQO, whose audio-model maximum is about 4.75. Prefer active clips around 8–10 seconds. Requires optional bindings and model data; do not compare these scores directly with ViSQOL speech mode."],
    pl: ["Szacuje postrzeganą jakość dźwięku z podobieństwa spektrogramów oryginału i sygnału przetworzonego.", "Używa oficjalnych wiązań Google ViSQOL i modelu SVR trybu audio; oba wejścia są przeliczane wielofazowo do 48 kHz. Podobieństwo czasowo-widmowe jest mapowane na MOS-LQO z maksimum modelu audio około 4,75. Preferowane są aktywne fragmenty około 8–10 sekund. Wymaga opcjonalnych wiązań i modelu; wyników nie należy bezpośrednio porównywać z trybem speech."],
  },
  LSD_METRIC: {
    en: ["Measures the difference between short-time log-magnitude spectra in decibels.", "Uses 32 ms Hann windows with 75% overlap and a −100 dBFS magnitude floor. For each frame it takes the RMS spectral difference in dB, then averages frames. Lower is closer to the reference. It exposes spectral changes but ignores phase differences that leave magnitudes unchanged; it is a diagnostic, not a MOS predictor."],
    pl: ["Mierzy różnicę krótkoczasowych logarytmicznych widm amplitudowych w decybelach.", "Używa okien Hanna 32 ms z nakładaniem 75% i dolnym ograniczeniem modułu −100 dBFS. Dla ramki liczy RMS różnic widma w dB, a następnie uśrednia ramki. Mniej oznacza większą zgodność z oryginałem. Ujawnia zmiany widmowe, ale pomija zmiany fazy bez zmiany modułu; to diagnostyka, nie predykcja MOS."],
  },
  MRSC_METRIC: {
    en: ["Measures relative spectral error at several time-frequency resolutions.", "Computes STFT magnitudes with 16, 32 and 64 ms windows and 75% overlap. At each resolution it divides the Frobenius norm of the magnitude error by the reference norm, then averages. Lower is better and zero indicates matching magnitudes. A silent reference is undefined; some phase changes remain invisible. This ratio is not a perceptual MOS."],
    pl: ["Mierzy względny błąd widma w kilku rozdzielczościach czasowo-częstotliwościowych.", "Liczy moduły STFT z oknami 16, 32 i 64 ms oraz nakładaniem 75%. Dla każdej rozdzielczości dzieli normę Frobeniusa błędu modułu przez normę oryginału i uśrednia wyniki. Mniej jest lepiej, a zero oznacza zgodne moduły. Dla cichego odniesienia wynik jest nieokreślony; część zmian fazy pozostaje niewidoczna. Ten iloraz nie jest percepcyjnym MOS."],
  },
  WSS_METRIC: {
    en: ["Compares the slopes of reference and processed speech spectra.", "Calculates differences between adjacent perceptual-band levels and weights slope mismatches, emphasising important spectral peaks. Lower distance means better preservation of spectral shape. Requires reference speech and aligned frames. It highlights spectral-envelope damage but does not directly measure intelligibility or payload recovery."],
    pl: ["Porównuje nachylenia widm oryginalnej i przetworzonej mowy.", "Oblicza różnice poziomów sąsiednich pasm percepcyjnych i waży niezgodność nachyleń, podkreślając istotne szczyty widma. Mniejsza odległość oznacza lepsze zachowanie kształtu widma. Wymaga mowy odniesienia i wyrównanych ramek. Ujawnia zmiany obwiedni widmowej, ale nie mierzy bezpośrednio zrozumiałości ani odczytu danych."],
  },
  LLR_METRIC: {
    en: ["Measures how much the linear-prediction model of speech changes after processing.", "Fits linear predictive coefficients to reference and processed frames, then evaluates a log ratio of prediction-error terms using the reference autocorrelation. Lower values indicate more similar spectral envelopes. It is intended for speech; silence, numerical conditioning and time alignment can affect the estimate."],
    pl: ["Mierzy zmianę modelu predykcji liniowej mowy po przetworzeniu.", "Dopasowuje współczynniki predykcji liniowej do ramek oryginału i wyniku, po czym oblicza logarytm ilorazu składników błędu z autokorelacją odniesienia. Niższa wartość oznacza bardziej podobne obwiednie widmowe. Miara jest przeznaczona do mowy; cisza, uwarunkowanie numeryczne i wyrównanie czasowe wpływają na estymację."],
  },
  CEPSTRUM_DISTANCE_METRIC: {
    en: ["Compares cepstral representations of reference and processed speech.", "Derives cepstral coefficients from short-frame speech models and computes their distance. Cepstral features describe spectral-envelope shape rather than individual waveform samples. Lower distance in dB means a closer envelope. It needs a reference and should be interpreted alongside other metrics, since matching envelopes do not imply identical phase or perceptual quality."],
    pl: ["Porównuje reprezentacje cepstralne oryginalnej i przetworzonej mowy.", "Wyznacza współczynniki cepstralne z modeli krótkich ramek mowy i oblicza ich odległość. Cechy cepstralne opisują obwiednię widma zamiast pojedynczych próbek. Mniejsza odległość w dB oznacza bliższą obwiednię. Wymaga odniesienia i interpretacji z innymi metrykami, bo podobne obwiednie nie gwarantują zgodnej fazy ani jakości słuchowej."],
  },
  MEL_CEPSTRAL_DISTANCE_METRIC: {
    en: ["Measures changes in speech spectral shape using a mel-scaled representation.", "Builds 20-band mel power spectrograms with a 1024-sample Hamming window and 256-sample hop, then passes them to the mel-cepstral-distance comparison library. Lower MCD means closer representations. Values depend on feature extraction and comparison settings, so scores from differently configured MCD implementations are not automatically interchangeable."],
    pl: ["Mierzy zmiany kształtu widma mowy w reprezentacji o skali melowej.", "Buduje 20-pasmowe melowe spektrogramy mocy z oknem Hamminga 1024 próbki i krokiem 256, a następnie przekazuje je do biblioteki mel-cepstral-distance. Niższe MCD oznacza bliższe reprezentacje. Wyniki zależą od ekstrakcji cech i ustawień porównania, więc wartości z różnych konfiguracji MCD nie są automatycznie porównywalne."],
  },
  SISDR_METRIC: {
    en: ["Measures waveform distortion after compensating for a single global scale factor.", "Projects the processed signal onto the reference and compares projected target energy with residual energy in dB. Higher SI-SDR is better. Unlike ordinary SNR, a uniform gain change is discounted; timing errors and other waveform changes still count. Use alongside level-sensitive metrics when amplitude preservation matters."],
    pl: ["Mierzy zniekształcenie przebiegu po kompensacji jednego globalnego współczynnika skali.", "Rzutuje sygnał przetworzony na oryginał i porównuje energię projekcji z energią reszty w dB. Wyższy SI-SDR jest lepszy. W odróżnieniu od zwykłego SNR pomija jednolite wzmocnienie; błędy czasu i inne zmiany przebiegu nadal wpływają na wynik. Jeśli ważne jest zachowanie amplitudy, warto zestawić go z miarą czułą na poziom."],
  },
  BSS_EVAL_METRIC: {
    en: ["Reports several distortion measures originally designed for source-separation evaluation.", "Uses museval BSS Eval v4 to decompose estimation errors into target-related, interference and artefact terms. Returns SDR, ISR, SIR and SAR in dB, plus a source permutation index. Higher is better for the four ratios; perm identifies source assignment and is not a quality score. Some components can be degenerate for single-source comparisons."],
    pl: ["Zwraca kilka miar zniekształceń opracowanych do oceny separacji źródeł.", "Używa museval BSS Eval v4 do rozłożenia błędów estymacji na składniki związane z celem, interferencją i artefaktami. Zwraca SDR, ISR, SIR i SAR w dB oraz indeks permutacji źródeł. Więcej jest lepiej dla czterech ilorazów; perm określa przypisanie źródła i nie jest oceną jakości. Przy porównaniu jednego źródła część składników może być zdegenerowana."],
  },
  CBAK_METRIC: {
    en: ["Predicts the perceived intrusiveness of background noise in processed speech.", "Combines PESQ, segmental SNR and weighted spectral slope through an empirical regression. The resulting composite score is limited to the 1–5 range, with higher values meaning less intrusive background noise. It is calibrated for speech enhancement and needs the original reference; it is not a direct measurement of background-noise power."],
    pl: ["Przewiduje dokuczliwość szumu tła w przetworzonej mowie.", "Łączy PESQ, segmentowy SNR i ważone nachylenie widma przez regresję empiryczną. Wynik złożony jest ograniczany do zakresu 1–5; więcej oznacza mniej dokuczliwe tło. Model skalibrowano dla poprawy jakości mowy i wymaga on oryginału; nie jest bezpośrednim pomiarem mocy szumu."],
  },
  CSIG_METRIC: {
    en: ["Predicts how much the speech signal itself sounds distorted.", "Combines PESQ, log-likelihood ratio and weighted spectral slope using an empirical regression, then limits the prediction to 1–5. Higher values mean better predicted speech-signal quality. It focuses on speech distortion rather than background-noise annoyance and is a model estimate, not a listener’s actual rating."],
    pl: ["Przewiduje, jak silnie zniekształcony brzmi sam sygnał mowy.", "Łączy PESQ, logarytmiczny iloraz wiarygodności i ważone nachylenie widma przez regresję empiryczną, po czym ogranicza wynik do 1–5. Więcej oznacza lepszą przewidywaną jakość samej mowy. Skupia się na zniekształceniu mowy, a nie dokuczliwości tła; jest estymacją modelu, nie rzeczywistą oceną słuchacza."],
  },
  COVL_METRIC: {
    en: ["Predicts overall speech quality, combining signal distortion and noise effects.", "Uses an empirical combination of PESQ, log-likelihood ratio and weighted spectral slope to produce a composite 1–5 score. Higher is better. The model was designed for speech-enhancement evaluation; its scale should not be treated as directly interchangeable with PESQ, MOSNet or a listening-test MOS."],
    pl: ["Przewiduje ogólną jakość mowy, łącząc wpływ zniekształcenia sygnału i szumu.", "Używa empirycznego połączenia PESQ, logarytmicznego ilorazu wiarygodności i ważonego nachylenia widma, tworząc ocenę 1–5. Więcej jest lepiej. Model służy ocenie poprawy jakości mowy; jego skali nie należy utożsamiać bezpośrednio z PESQ, MOSNet ani MOS z testu odsłuchowego."],
  },
  STOI_METRIC: {
    en: ["Estimates speech intelligibility from preservation of short-time spectral envelopes.", "Compares reference and processed temporal envelopes in one-third-octave bands over short segments, after the algorithm’s normalisation and clipping steps. Higher values, commonly near the 0–1 range, suggest better intelligibility. It does not recognise words: the score is not a percentage of correctly understood words and is not a general music-quality metric."],
    pl: ["Szacuje zrozumiałość mowy na podstawie zachowania krótkoczasowych obwiedni widmowych.", "Porównuje obwiednie czasowe oryginału i wyniku w pasmach tercjowych oraz krótkich segmentach, po normalizacji i ograniczaniu przewidzianym w algorytmie. Wyższy wynik, zwykle w pobliżu zakresu 0–1, sugeruje lepszą zrozumiałość. Nie rozpoznaje słów: wynik nie jest procentem zrozumianych wyrazów ani ogólną miarą jakości muzyki."],
  },
  ESTOI_METRIC: {
    en: ["Extends STOI with a spectro-temporal comparison useful for fluctuating interference.", "Uses pystoi in extended mode, comparing normalised short-time time-frequency envelope patterns. Higher eSTOI indicates better predicted speech intelligibility, usually on an index scale near 0–1. It requires reference speech and remains a proxy: it does not measure listening quality, message decoding or steganographic security."],
    pl: ["Rozszerza STOI o porównanie czasowo-widmowe przydatne dla zmiennych zakłóceń.", "Korzysta z rozszerzonego trybu pystoi i porównuje znormalizowane krótkoczasowe wzorce obwiedni czasowo-częstotliwościowych. Wyższe eSTOI oznacza lepszą przewidywaną zrozumiałość mowy, zwykle w skali bliskiej 0–1. Wymaga mowy odniesienia i pozostaje wskaźnikiem zastępczym: nie mierzy jakości odsłuchu, odczytu danych ani bezpieczeństwa steganografii."],
  },
  CSII_METRIC: {
    en: ["Estimates intelligibility using coherence between reference and processed speech.", "Computes coherence-based signal-to-distortion information in weighted frequency bands. Returns separate high, mid and low indices for speech segments at different levels. Higher values indicate better preserved intelligibility cues. The three components describe different portions of speech and should not be mistaken for repeated measurements of one global score."],
    pl: ["Szacuje zrozumiałość z koherencji oryginalnej i przetworzonej mowy.", "Oblicza informację o stosunku sygnału do zniekształceń na podstawie koherencji w ważonych pasmach. Zwraca osobne indeksy high, mid i low dla segmentów mowy o różnych poziomach. Wyższe wartości oznaczają lepiej zachowane wskazówki zrozumiałości. Trzy składowe opisują różne części mowy, a nie powtórzenia jednego wyniku globalnego."],
  },
  NCM_METRIC: {
    en: ["Measures preservation of slow speech-envelope modulations across frequency bands.", "Splits speech into 20 bands, extracts Hilbert envelopes and resamples them to 32 Hz. Normalised envelope covariance is mapped to apparent SNR and combined using speech-importance weights. Higher scores indicate better predicted intelligibility. This implementation accepts 8 or 16 kHz input and requires a reference; it does not assess bit recovery."],
    pl: ["Mierzy zachowanie wolnych modulacji obwiedni mowy w pasmach częstotliwości.", "Dzieli mowę na 20 pasm, wyznacza obwiednie Hilberta i przelicza je do 32 Hz. Znormalizowana kowariancja obwiedni jest mapowana na pozorny SNR i łączona wagami ważności pasm mowy. Wyższy wynik oznacza lepszą przewidywaną zrozumiałość. Ta implementacja przyjmuje wejście 8 lub 16 kHz i wymaga oryginału; nie ocenia odczytu bitów."],
  },
  STGI_METRIC: {
    en: ["Estimates how many local spectro-temporal speech patterns remain sufficiently preserved.", "Resamples speech to 10 kHz, builds log-mel spectrograms and applies spectro-temporal Gabor filters. Normalised local similarities are compared with channel-specific thresholds; the score averages the resulting preserved-pattern decisions. Higher is better on a 0–1 scale. Sufficient speech duration is needed for the analysis windows; the result is not a word-recognition rate."],
    pl: ["Szacuje, ile lokalnych wzorców czasowo-widmowych mowy zachowało wystarczającą zgodność.", "Przelicza mowę do 10 kHz, buduje logarytmiczne spektrogramy melowe i stosuje czasowo-widmowe filtry Gabora. Znormalizowane podobieństwa lokalne są porównywane z progami kanałów, a wynik uśrednia decyzje o zachowaniu wzorców. Więcej jest lepiej w skali 0–1. Potrzebna jest długość mowy wystarczająca dla okien analizy; to nie odsetek rozpoznanych słów."],
  },
  WSTMI_METRIC: {
    en: ["Predicts intelligibility from weighted spectro-temporal modulation similarities.", "Computes log-mel features and Gabor modulation responses after conversion to 10 kHz. Normalised reference-to-processed correlations are combined with fixed learned weights and a bias. Higher values indicate better predicted intelligibility. This is an index, not a percentage or MOS; interpret it consistently within the same implementation and speech domain."],
    pl: ["Przewiduje zrozumiałość z ważonych podobieństw modulacji czasowo-widmowych.", "Po konwersji do 10 kHz oblicza cechy log-mel i odpowiedzi filtrów modulacyjnych Gabora. Znormalizowane korelacje oryginału z wynikiem łączy stałymi wyuczonymi wagami i wyrazem wolnym. Wyższa wartość oznacza lepszą przewidywaną zrozumiałość. To indeks, a nie procent ani MOS; należy porównywać go w tej samej implementacji i domenie mowy."],
  },
  SRMR_METRIC: {
    en: ["Estimates reverberation-related degradation from the processed signal alone.", "Analyses modulation energy in auditory-band envelopes and forms a ratio of lower to higher modulation-frequency energy. Higher SRMR generally suggests less reverberant degradation for speech. It does not require a clean reference and is not a direct RT60 estimate. Noise, speaking style and signal content can also influence its value."],
    pl: ["Szacuje degradację związaną z pogłosem na podstawie samego sygnału przetworzonego.", "Analizuje energię modulacji obwiedni w pasmach słuchowych i tworzy stosunek energii niższych do wyższych częstotliwości modulacji. Wyższe SRMR zwykle sugeruje mniejszą degradację pogłosową mowy. Nie wymaga czystego oryginału i nie jest bezpośrednią estymacją RT60. Na wynik wpływają też szum, sposób mówienia i treść sygnału."],
  },
  BSD_METRIC: {
    en: ["Measures reference-relative spectral distortion on the Bark auditory scale.", "Maps short-time power spectra into 32 Bark bands and averages the squared band-energy error normalised by reference band energy. Lower values mean closer spectra. Although grouped with reverberation metrics, it responds to other spectral changes as well and is not a direct measurement of room reverberation time."],
    pl: ["Mierzy zniekształcenie widmowe względem oryginału w słuchowej skali Bark.", "Mapuje krótkoczasowe widma mocy do 32 pasm Bark i uśrednia kwadrat błędu energii pasm normalizowany energią odniesienia. Niższy wynik oznacza bliższe widma. Choć znajduje się w grupie metryk pogłosu, reaguje także na inne zmiany widmowe i nie mierzy bezpośrednio czasu pogłosu pomieszczenia."],
  },
  AI_MOSNET_METRIC: {
    en: ["Predicts speech quality using a pretrained neural network rather than a samplewise reference comparison.", "Feeds magnitude spectrograms through convolutional and bidirectional LSTM layers and averages frame predictions. TAF evaluates cover and processed audio independently, returning both scores; only processed is ranked as the result. Higher predicts better quality. Requires TensorFlow and model weights; predictions depend on the training domain and are not actual listener ratings."],
    pl: ["Przewiduje jakość mowy wytrenowaną siecią neuronową zamiast porównywać próbki z oryginałem.", "Przekazuje spektrogramy amplitudowe przez warstwy konwolucyjne i dwukierunkowe LSTM, po czym uśrednia predykcje ramek. TAF ocenia oryginał i wynik niezależnie, zwracając oba wyniki; tylko processed podlega rankingowi jako rezultat. Więcej oznacza lepszą przewidywaną jakość. Wymaga TensorFlow i wag; oceny zależą od danych treningowych i nie są rzeczywistymi ocenami słuchaczy."],
  },
};

export const catalogueDescriptions = { methods, attacks, metrics };

export function catalogueDescription(kind: CatalogueKind, name: string, locale: Locale) {
  return catalogueDescriptions[kind][name]?.[locale];
}
