"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 22:48:16.512521
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('corpus_id', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=40), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_kind'), 'datasets', ['kind'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('experiment_type', sa.String(length=40), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_archived'), 'experiments', ['archived'], unique=False)
    op.create_index(op.f('ix_experiments_experiment_type'), 'experiments', ['experiment_type'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('experiment_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('completed_rows', sa.Integer(), nullable=False),
    sa.Column('ok_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_created_at'), 'runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_runs_experiment_id'), 'runs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('result_rows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=400), nullable=False),
    sa.Column('method', sa.String(length=300), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=True),
    sa.Column('payload_length', sa.Integer(), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=False),
    sa.Column('attack', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_kind', sa.String(length=40), nullable=True),
    sa.Column('ber', sa.Float(), nullable=True),
    sa.Column('decode_success', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_result_rows_run_attack', 'result_rows', ['run_id', 'attack'], unique=False)
    op.create_index('ix_result_rows_run_method', 'result_rows', ['run_id', 'method'], unique=False)
    op.create_index('ix_result_rows_run_ordinal', 'result_rows', ['run_id', 'ordinal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_result_rows_run_ordinal', table_name='result_rows')
    op.drop_index('ix_result_rows_run_method', table_name='result_rows')
    op.drop_index('ix_result_rows_run_attack', table_name='result_rows')
    op.drop_table('result_rows')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_experiment_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_created_at'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_experiments_experiment_type'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_archived'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_datasets_kind'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
